### ISSUE TITLE
Web.py processSockets is O(n) instead of O(1)

### ISSUE THREAD

**Issue by odeits** [jkingsman/Mockbox#14]
if openSockets were a dictionary keyed on on socket.id then lookup and processing of the sockets will scale. 

In a similar vein, encoding the json once then sending it to all clients will save rebuilding and re-encoding for each duplicate client.

**Comment by jkingsman** [comment]
Good call on the openSockets keying.

It should actually be impossible for more than one client to share an address; the addresses are generated per websocket connection. So I agree with you, but practically, there's no benefit to be gained I don't think.

**Comment by odeits** [comment]
Since you have a live demo running I would think it would effect that one the most. Wouldn't want your project to get hugged to death.

**Comment by jkingsman** [comment]
Yeah definitely; good call. I'll implement that if I can escape the family later today.
