### ISSUE TITLE
How can I change port for HTTP ?

### ISSUE THREAD

**Issue by dszymczuk** [jkingsman/Mockbox#22]

**Comment by jkingsman** [comment]
There's no way to do this in a config file right now; until then, change the reactor listening port at https://github.com/jkingsman/Mockbox/blob/master/Web.py#L44 or in the corresponding other conditional for HTTPS.

**Comment by dszymczuk** [comment]
Maybe add new param to define this port ? (default use 80).

When you use Apache or Nginx on 80 port, you probably can see default page from Apache or Nginx.

**Comment by jkingsman** [comment]
I'm not sure what you mean with Apache or Nginx, but I'll try to get a patch out to do this through config later today.
